# this configuration will look similar to the native Tobiko Cloud scheduler 
# but will leverage your hybrid runners instead of Tobiko Cloud's compute
gateways:
  databricks:
    scheduler:
      type: cloud
      default_catalog: rde_development
    variables: # these are variables in your original config.py file
      catalog_src: catalog_src_placeholder # TODO: replace with actual catalog
      base: base
      global_start_date: '2005-01-01'
      minimum_observation_period_start_date: '2005-01-01'

default_gateway: databricks

model_defaults:
  dialect: databricks
  start: '2005-01-01'
  cron: "@daily"
  owner: "LTH DST"
  kind: VIEW

format:
  append_newline: true
  normalize: true
  indent: 2
  normalize_functions: lower
  leading_comma: false
  max_text_width: 80

# gives you prevention guardrails to catch issues before you run your models in databricks
linter:
  enabled: true
  # error if ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"] rules violated
  rules: ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"]
  # warn_rules: ["noselectstar"]
  # ignored_rules: ["noselectstar"]