name: SQLMesh Workflow
on:
  pull_request:
    types:
    - synchronize
    - opened
  # Required if using comments to issue commands to the bot
  issue_comment:
    types:
    - created
  # Required if using required approvers to automate deployments
  pull_request_review:
    types:
    - edited
    - submitted
    - dismissed
     
jobs:
  Deploy-SQLMesh-Dev:
    uses: ./.github/workflows/tcloud_cicd.yaml
    name: Deploy SQLMesh Dev
    secrets: inherit
    with:
      vm-image: dev-vm-001
      environment: Dev
 
  Deploy-SQLMesh-Prod:
    uses: ./.github/workflows/tcloud_cicd.yaml
    needs: Deploy-SQLMesh-Dev
    name: Deploy SQLMesh Prod
    if: contains(github.ref, 'release/')
    secrets: inherit
    with:
      vm-image: prod-vm-01
      environment: Prod